### ISSUE TITLE
Terraform 0.9.5: crash related to Volumes and scaleway.resourceScalewayServerRead 

### ISSUE THREAD

**Issue by talkdirty** [terraform-providers/terraform-provider-scaleway#12] opened 2017-06-28 17:54 UTC
Terraform crashes on every subsequent operation that touches `terraform.tfstate` (apply, destroy, plan) after an (addmitedly incorrect) Volume attachment has been made. Crash log is attached.

Here's what I did last:

I wrote this small module which is responsible for creating and attaching volumes to my servers:
```terraform
variable "for_servers" { type = "list" }
variable "count" {}
variable "volume_size" {}
variable "enabled" {}

resource "scaleway_volume" "volume" {
    count = "${var.enabled? var.count : 0}"
    name  = "kube-data-${count.index}"
    size_in_gb  = "${var.volume_size}"
    type  = "l_ssd"
}

resource "scaleway_volume_attachment" "volume-attachment" {
    count = "${var.enabled? var.count : 0}"
    server = "${element(var.for_servers, count.index)}"
    volume = "${element(scaleway_volume.volume.*.id, count.index)}"
}

output "volume_ids" {
    value = ["${scaleway_volume.volume.*.id}"]
}

output "volume_attachment_ids" {
    value = ["${scaleway_volume_attachment.volume-attachment.*.id}"]
}
```

`for_servers` is called with the `output` of the `scaleway_server` resource, so this module runs after my servers have been created.

Here's what I think caused the crash (I'm not sure though)

Thing is, I've tried this on `VCS1` Servers, which don't allow attaching more than a total of `50GB` to the Server. The OS Volume + the Volume that are created with the above Module total `100GB`.

There seems to be a Design flaw in Scaleways API: it allows attaching more than 50GB of Volumes to `VCS1` Servers, but if that's the case the Servers won't start (you can try this in Scaleways Web UI).

Anyways, the `scaleway_volume_attachment`'s from the above Module run indefinitely in this configuration when applying. After aborting, the crash you can inspect in the crash log occurs.

[crash.log.txt](https://github.com/terraform-providers/terraform-provider-scaleway/files/1109536/crash.log.txt)

Since the exception occurs in `resource_scaleway_server.go:205`, I'll also include the module with which I create the Servers here:

```terraform
data "scaleway_image" "ubuntu" {
    architecture = "x86_64"
    name = "Ubuntu Xenial"
}

resource "scaleway_server" "kube-node" {
   name = "${var.name}-${count.index}"

   image = "${data.scaleway_image.ubuntu.id}"
   
   # 2 X86_64 Cores, 2 GB Memory, 2,99€/Month
   type = "VC1S"

   security_group = "${var.security_group_id}"

   count = "${var.count}"

   enable_ipv6 = true
   dynamic_ip_required = true

   tags = ["${count.index}", "tf-managed"]

   connection {
       type = "ssh"
       user = "root"
       private_key = "${file(var.ssh_key)}"
   }

   provisioner "remote-exec" {
        scripts = [
            "scripts/install-kubeadm.sh"
        ]
   }
}

output "vm_ips" {
    value = ["${scaleway_server.kube-node.*.public_ip}"]
}

output "vm_ids" {
    value = ["${scaleway_server.kube-node.*.id}"]
}
```

**Comment by talkdirty** [comment] 2017-06-28 18:43
I just tried it with `C2S` nodes because they allow attaching an additional 50GB Volume and it works flawlessly, so something going wrong with `scaleway_volume_attachment` as described above seems likely

**Comment by nicolai86** [comment] 2017-06-28 21:05
thanks for the bug report, @talkdirty . I'll take a look at it as soon as I can.

**Comment by nicolai86** [comment] 2017-08-25 23:27
@talkdirty the latest version of the provider (0.1.1) contained a bugfix for `scaleway_volume_attachment`. I think this might fix this issue, too. Can you verify if it solves the issue you have encountered?

**Comment by nicolai86** [comment] 2017-10-07 06:17
Closing due to age - I couldn't reproduce this issue with the latest version of the provider.

**Closed by nicolai86** 2017-10-07 06:17 UTC
Labels: bug, crash, waiting-response
