### ISSUE TITLE
Bug in the re-apply operation

### ISSUE THREAD

**Issue by remyleone** [terraform-providers/terraform-provider-scaleway#103] opened 2018-12-12 09:59 UTC
### Terraform Version

```
$ terraform version
Terraform v0.11.10
+ provider.scaleway (unversioned)
```

### Affected Resource(s)

- scaleway_server

### Terraform Configuration Files

```hcl
variable "organization" {}
variable "token" {}

provider "scaleway" {
  organization = "${var.organization}"
  token        = "${var.token}"
  region       = "par1"
}

resource "scaleway_ip" "ip" {
}

resource "scaleway_server" "ubuntu-apache-server" {
  name  = "ubuntu-apache-server"
  public_ip = "${scaleway_ip.ip.ip}"
  image = "d4067cdc-dc9d-4810-8a26-0dae51d7df42"
  type  = "START1-S"
}


resource "scaleway_security_group" "http" {
  name        = "http"
  description = "allow HTTP and HTTPS traffic"
}

resource "scaleway_security_group_rule" "http_accept" {
  security_group = "${scaleway_security_group.http.id}"

  action    = "accept"
  direction = "inbound"
  ip_range  = "0.0.0.0/0"
  protocol  = "TCP"
  port      = 80
}

resource "scaleway_security_group_rule" "https_accept" {
  security_group = "${scaleway_security_group.http.id}"

  action    = "accept"
  direction = "inbound"
  ip_range  = "0.0.0.0/0"
  protocol  = "TCP"
  port      = 443
}
```

### Expected Behavior

Terraform should tell that there is nothing to do 

### Actual Behavior

Terraform offers to destroy and recreate the resource:

```
$ terraform apply
var.organization

var.token

scaleway_security_group.http: Refreshing state... (ID: 9febcff9-61eb-4efe-9729-9f35eea76be0)
scaleway_ip.ip: Refreshing state... (ID: 8ed1c207-86db-4e60-84cd-0a4e84031239)
scaleway_server.ubuntu-apache-server: Refreshing state... (ID: 1728d050-fc19-45e3-8c6e-2db1ad42a587)
scaleway_security_group_rule.http_accept: Refreshing state... (ID: 7b7e4ee4-2cd0-4c96-a0a9-50c02d6ed5ba)
scaleway_security_group_rule.https_accept: Refreshing state... (ID: c30bdb44-1ba5-4f85-8c02-d808d7f81a20)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ scaleway_server.ubuntu-apache-server (new resource required)
      id:           "1728d050-fc19-45e3-8c6e-2db1ad42a587" => <computed> (forces new resource)
      boot_type:    "bootscript" => <computed>
      cloudinit:    "" => <computed>
      enable_ipv6:  "false" => "false"
      image:        "" => "d4067cdc-dc9d-4810-8a26-0dae51d7df42" (forces new resource)
      name:         "ubuntu-apache-server" => "ubuntu-apache-server"
      private_ip:   "10.16.228.135" => <computed>
      public_ip:    "51.15.253.183" => "51.15.253.183"
      public_ipv6:  "" => <computed>
      state:        "running" => <computed>
      state_detail: "booted" => <computed>
      type:         "START1-S" => "START1-S"


Plan: 1 to add, 0 to change, 1 to destroy.
```

What actually happened?

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`
1. `terraform apply`

**Comment by sblaisot** [comment] 2018-12-12 10:33
1. You have shared your api credentials. please revoke them asap on scaleway's console to avoid malicious people using them to order server with your account and billing information
2. This seems to be a duplicate of #95 
3. You can avoid this by adding **inside** your `scaleway_server` resource:

```
  lifecycle {
    ignore_changes = ["image"]
  }
```

**Comment by sieben** [comment] 2018-12-12 10:35
thanks @sblaisot those tokens are revoked

**Comment by nicolai86** [comment] 2018-12-12 16:41
this looks like it’s related to an issue reading the underlying server information; needs investigation

**Comment by jerome-quere** [comment] 2020-02-28 14:43
Hi, @remyleone `scaleway_server` resource has been deprecated in favor of `scaleway_insance_server`. TY for your feedback.
 I am closing this one now

**Closed by jerome-quere** 2020-02-28 14:43 UTC
Labels: bug
